# NumPy

## 1-d Array

In [1]:
import numpy as np
arr=np.array([3,6,9])  
print(arr)
print(type(arr))
a=np.zeros(3)
b=np.ones(6)
c=np.arange(10)
d=np.arange(2,10)   
e=np.arange(1,10,2) # incrementsw by 2
print(a)
print(b)
print(c)
print(d)
print(e)

[3 6 9]
<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## N-d Array

In [4]:
import numpy as np
# create a 2-d array
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])  
arr2=np.array([['a','b','c'],['d','e','f']])
   
#creates a 3X3 array with all zeros
zeros=np.zeros((3,3))
   
#creates a 2X2 array with all ones
ones=np.ones((2,4),dtype='int')  #specify the type with (dtype) parameter 
   
print(arr1)
print(arr2)
print(zeros)
print(ones)
# ndim
a=np.array([[[1, 2, 3], [4, 5, 6]], [[6, 4, 3], [1, 9, 6]]])
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['a' 'b' 'c']
 ['d' 'e' 'f']]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
3


## operations

In [8]:
import numpy as aj
arr1=aj.array([3,4,5,6])
arr2=aj.array([7,3,4,3])
c=arr1+arr2
d=arr1-arr2
e=arr1/arr2
print(arr1)
print(arr2)
print(c) # addition
print(d) # subtraction
print(e) # division
print("Multiplying 2 to all elements:",c*2)
print("Subtracting one from all elements:",d-1)

[3 4 5 6]
[7 3 4 3]
[10  7  9  9]
[-4  1  1  3]
[0.42857143 1.33333333 1.25       2.        ]
Multiplying 2 to all elements: [20 14 18 18]
Subtracting one from all elements: [-5  0  0  2]


## Array Indexing

In [11]:
import numpy as np
ar1= np.array([3,2,3,4])
ar2= np.array(['A','j','a','y',' ','F','l','a','m','e','n'])
ar3= np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(ar1[0]) # prints first element
print(ar1[-1]) # prints last element
print(ar2)
print(ar2[2]) # prints third element
print(ar2[4]) # prints 4th index, here its a blank space
print(ar3[1][3]) #prints 9
print(ar3[1,3]) # Or you can use this type 

3
4
['A' 'j' 'a' 'y' ' ' 'F' 'l' 'a' 'm' 'e' 'n']
a
 
9
9


## Array slicing

In [16]:
import numpy as np
arr=np.array(['A','s','j','s','a','s','y'])
arr1=np.array(['A','j','a','y','F','l','a','m','e','n'])
arr2=np.array([1,2,3,4,5,6,7,8,9])
arr3=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
   
print(arr1[:4]) # default is taken as 0
print(arr1[0:3])
print(arr1[4:]) # taken till the end
print(arr[::2])
print(arr2[-7:-1:2])
print(arr2[::2]) # step size as 2
   
# 2-D Slicing
print(arr3[1,1:4])
print(arr3[0:2, 2])
print(arr3[0:2, 1:4])

['A' 'j' 'a' 'y']
['A' 'j' 'a']
['F' 'l' 'a' 'm' 'e' 'n']
['A' 'j' 'a' 'y']
[3 5 7]
[1 3 5 7 9]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


## Array shape and reshape

In [25]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1= np.array([1,2,3,4])
print(arr.shape)
print(arr1.shape)
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
print('No of dimensions of the array:',array_example.ndim)
print('Total no of elements of the array:',array_example.size) 
print('Shape of the array:',array_example.shape)  

# 1-d to 2-d
ar1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newar1 = ar1.reshape(3, 4)
ar2 = np.array(['A','j','a','y','F','l','a','m','e','n'])
newar2 = ar2.reshape(2,5)
print(newar1)
print(newar2)
# 1-d to 3-d
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = a.reshape(2, 3, 2)
print(newarr)
# n-d to 1-d
a1 = np.array([[1, 2, 3], [4, 5, 6]])
newarr = a1.reshape(-1)
print(newarr)

(2, 4)
(4,)
No of dimensions of the array: 3
Total no of elements of the array: 24
Shape of the array: (3, 2, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[['A' 'j' 'a' 'y' 'F']
 ['l' 'a' 'm' 'e' 'n']]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## **NumPy Sorting and Searching**

In [26]:
import numpy as np
arr1 = np.array([3, 2, 0, 1])
arr2 = np.array(['red','blue','green'])
arr3 = np.array([[3, 2, 4], [5, 0, 1]])   
print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(arr3))
#where()
arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr1 == 4)
y = np.where(arr1%2 == 0)
z = np.where(arr1%2 == 1)
print(x)
print(y)
print(z)
#searchsorted())
arr1 = np.array([6, 12, 8, 7])
x = np.searchsorted(arr1, 7)
print(x)
# Multiple values
arr2 = np.array([1, 3, 5, 7])
y = np.searchsorted(arr2, [1, 6, 4])
print(y)

[0 1 2 3]
['blue' 'green' 'red']
[[2 3 4]
 [0 1 5]]
(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)
1
[0 3 2]


## Mean Median Mode

In [32]:
import numpy as np
# mean
arr=np.array([1,1,1])
x=np.mean(arr)
print(x)
# median for one value in the mddle
speed = [1,3,3,6,7,8,9]
x = np.median(speed)
print(x)
   
# median for two values in the middle
speed1 = [99,86,87,88,86,103,87,94,78,77,85,86]
y = np.median(speed1)
print(y)
#mode
from scipy import stats
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
x = stats.mode(speed)
print(x)

#Standard deviation
speed = [86,87,88,86,87,85,86]
x = np.std(speed)
print(x)
 
speed1 = [32,111,138,28,59,77,97]
y = np.std(speed1)
print(y)

1.0
6.0
86.5
ModeResult(mode=array([86]), count=array([3]))
0.9035079029052513
37.84501153334721
